services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: /run/secrets/MYSQL_PASSWORD
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    secrets:
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 30s
      timeout: 3s
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: /run/secrets/MYSQL_PASSWORD
      MARIADB_AUTO_UPGRADE: '1'
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - mysql:/var/lib/mysql

volumes:
  data:
  letsencrypt:
  mysql:

secrets:
  MYSQL_ROOT_PASSWORD:
    file: /share/Volumes/nginxpm/.secrets/mysqlrootpassword.txt
  MYSQL_PASSWORD:
    file: /share/Volumes/nginxpm/.secrets/mysqlpassword.txt
